-- Cosmetic FK renames generated by Prisma.
-- On some databases these truncated constraint names never existed
-- (e.g. log_configuration_id FKs are added in a later migration).
-- Rename only when the source constraint is present.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'log_configuration_user_data_type_options_log_configuration_id_f'
      AND conrelid = 'log_configuration_user_data_type_options'::regclass
  ) THEN
    ALTER TABLE "log_configuration_user_data_type_options"
      RENAME CONSTRAINT "log_configuration_user_data_type_options_log_configuration_id_f"
      TO "log_configuration_user_data_type_options_log_configuration_fkey";
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'log_configuration_user_insitu_test_types_log_configuration_id_f'
      AND conrelid = 'log_configuration_user_insitu_test_types'::regclass
  ) THEN
    ALTER TABLE "log_configuration_user_insitu_test_types"
      RENAME CONSTRAINT "log_configuration_user_insitu_test_types_log_configuration_id_f"
      TO "log_configuration_user_insitu_test_types_log_configuration_fkey";
  END IF;
EXCEPTION
  WHEN undefined_table THEN
    NULL; -- table created in a later migration
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'log_configuration_user_insitu_unit_settings_log_configuration_i'
      AND conrelid = 'log_configuration_user_insitu_unit_settings'::regclass
  ) THEN
    ALTER TABLE "log_configuration_user_insitu_unit_settings"
      RENAME CONSTRAINT "log_configuration_user_insitu_unit_settings_log_configuration_i"
      TO "log_configuration_user_insitu_unit_settings_log_configurat_fkey";
  END IF;
EXCEPTION
  WHEN undefined_table THEN
    NULL; -- table created in a later migration
END $$;
