-- Refresh lab test type templates from Tablogs catalog (result fields + alias tables).
INSERT INTO "lab_test_type_templates" (
  "module_slug",
  "option_key",
  "name",
  "graphic",
  "external_alias",
  "alias_table",
  "add_as_selected_data_plot",
  "active",
  "lab_test_result_fields",
  "sort_order",
  "created_at",
  "updated_at"
) VALUES
(
  'lab-tests',
  'moisture-content',
  'Moisture Content',
  'graphic_00.png',
  NULL,
  'Moisture Content',
  true,
  true,
  '[{"id":"result-field-1","name":"Results","externalAlias":null,"tablogsAlias":"Moisture Content (%)"}]'::jsonb,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'particle-size-distribution',
  'Particle Size Distribution',
  'graphic_00.png',
  NULL,
  'Particle Size Distribution',
  true,
  true,
  '[{"id":"result-field-1","name":"Sieve 0.075mm","externalAlias":null,"tablogsAlias":null},{"id":"result-field-2","name":"Sieve 0.21mm","externalAlias":null,"tablogsAlias":null},{"id":"result-field-3","name":"Sieve 0.6mm","externalAlias":null,"tablogsAlias":null},{"id":"result-field-4","name":"Sieve 2.36mm","externalAlias":null,"tablogsAlias":null},{"id":"result-field-5","name":"Sieve 6.7mm","externalAlias":null,"tablogsAlias":null},{"id":"result-field-6","name":"Sieve 19mm","externalAlias":null,"tablogsAlias":null},{"id":"result-field-7","name":"Sieve 63mm","externalAlias":null,"tablogsAlias":null},{"id":"result-field-8","name":"Sieve 200mm","externalAlias":null,"tablogsAlias":null},{"id":"result-field-9","name":"D60","externalAlias":null,"tablogsAlias":null},{"id":"result-field-10","name":"D30","externalAlias":null,"tablogsAlias":null},{"id":"result-field-11","name":"D10","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  1,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'atterberg-limits',
  'Atterberg Limits',
  'graphic_00.png',
  NULL,
  'Atterberg Limits',
  true,
  true,
  '[{"id":"result-field-1","name":"Plasticity Index % (PI)","externalAlias":null,"tablogsAlias":"Plasticity Index % (PI)"},{"id":"result-field-2","name":"Plasticity Limit% (PL)","externalAlias":null,"tablogsAlias":"Plasticity Limit % (PL)"},{"id":"result-field-3","name":"Liquid Limit % (LL)","externalAlias":null,"tablogsAlias":"Liquid Limit % (LL)"}]'::jsonb,
  2,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'is50',
  'IS50',
  'graphic_00.png',
  NULL,
  'IS50',
  true,
  true,
  '[{"id":"result-field-1","name":"Axial","externalAlias":null,"tablogsAlias":"Axial"},{"id":"result-field-2","name":"Diametral","externalAlias":null,"tablogsAlias":"Diametral"}]'::jsonb,
  3,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'gs-mechanical-grain-size',
  'GS - Mechanical Grain Size',
  'graphic_00.png',
  NULL,
  'GS - Mechanical Grain Size with Hydrometer',
  true,
  true,
  '[{"id":"result-field-1","name":"%Fines","externalAlias":null,"tablogsAlias":null},{"id":"result-field-2","name":"%Sand","externalAlias":null,"tablogsAlias":"% Sand"},{"id":"result-field-3","name":"%Gravel","externalAlias":null,"tablogsAlias":"% Gravel"}]'::jsonb,
  4,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'w-moisture-content',
  'w - Moisture Content',
  'graphic_00.png',
  NULL,
  'Moisture Content',
  true,
  true,
  '[{"id":"result-field-1","name":"w","externalAlias":null,"tablogsAlias":"Moisture Content (%)"}]'::jsonb,
  5,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'c-consolidation-test',
  'C - Consolidation Test',
  'graphic_00.png',
  NULL,
  'C - Consolidation Test',
  true,
  true,
  '[{"id":"result-field-1","name":"C","externalAlias":null,"tablogsAlias":"C"}]'::jsonb,
  6,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'l-pile',
  'L-Pile',
  'graphic_00.png',
  NULL,
  'L-Pile',
  true,
  true,
  '[{"id":"result-field-1","name":"KS","externalAlias":null,"tablogsAlias":"KS"},{"id":"result-field-2","name":"KC","externalAlias":null,"tablogsAlias":"KC"},{"id":"result-field-3","name":"E50","externalAlias":null,"tablogsAlias":"E50"}]'::jsonb,
  7,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'hcsi',
  'HCSI',
  'graphic_00.png',
  NULL,
  'HCSI',
  true,
  true,
  '[{"id":"result-field-1","name":"HCSI Index","externalAlias":null,"tablogsAlias":"HCSI Index"}]'::jsonb,
  8,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'dr-relative-density',
  'DR - Relative Density',
  'graphic_00.png',
  NULL,
  'DR - Relative Density',
  true,
  true,
  '[{"id":"result-field-1","name":"DR","externalAlias":null,"tablogsAlias":"Relative Density"}]'::jsonb,
  9,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'k-permeability-coefficient',
  'k - Permeability Coefficient',
  'graphic_00.png',
  NULL,
  'k - Permeability Coefficient',
  true,
  true,
  '[{"id":"result-field-1","name":"k","externalAlias":null,"tablogsAlias":"k"}]'::jsonb,
  10,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'q-triaxial-test',
  'q - Triaxial Test',
  'graphic_00.png',
  NULL,
  'q - Triaxial Compression Test',
  true,
  true,
  '[{"id":"result-field-1","name":"q","externalAlias":null,"tablogsAlias":"Triaxial"}]'::jsonb,
  11,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'ucs-unconfined-compressive-strength',
  'UCS - Unconfined Compressive Strength',
  'graphic_00.png',
  NULL,
  'UCS - Unconfined Compressive Strength',
  true,
  true,
  '[{"id":"result-field-1","name":"UCS","externalAlias":null,"tablogsAlias":"UCS (MPa)"}]'::jsonb,
  12,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'sb-shear-box-test',
  'SB - Shear Box Test',
  'graphic_00.png',
  NULL,
  'SB - Shear Box Test',
  true,
  true,
  '[{"id":"result-field-1","name":"SB","externalAlias":null,"tablogsAlias":"SB"}]'::jsonb,
  13,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'y-unit-weight',
  'Y - Unit Weight',
  'graphic_00.png',
  NULL,
  'Wet Unit Weight',
  true,
  true,
  '[{"id":"result-field-1","name":"Y","externalAlias":null,"tablogsAlias":"Wet Unit Weight"}]'::jsonb,
  14,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'yd-dry-unit-weight',
  'Yd - Dry Unit Weight',
  'graphic_00.png',
  NULL,
  'Dry Unit Weight',
  true,
  true,
  '[{"id":"result-field-1","name":"Yd","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  15,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'p-density',
  'p - Density',
  'graphic_00.png',
  NULL,
  'Density',
  true,
  true,
  '[{"id":"result-field-1","name":"p","externalAlias":null,"tablogsAlias":"p - Density"}]'::jsonb,
  16,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'pd-dry-density',
  'Pd - Dry Density',
  'graphic_00.png',
  NULL,
  'Dry Density',
  true,
  true,
  '[{"id":"result-field-1","name":"Pd","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  17,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("module_slug", "option_key") DO UPDATE SET
  "name" = EXCLUDED."name",
  "graphic" = EXCLUDED."graphic",
  "external_alias" = EXCLUDED."external_alias",
  "alias_table" = EXCLUDED."alias_table",
  "add_as_selected_data_plot" = EXCLUDED."add_as_selected_data_plot",
  "active" = EXCLUDED."active",
  "lab_test_result_fields" = EXCLUDED."lab_test_result_fields",
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = CURRENT_TIMESTAMP;

UPDATE "user_lab_test_types" AS u
SET
  "name" = t."name",
  "graphic" = t."graphic",
  "external_alias" = t."external_alias",
  "alias_table" = t."alias_table",
  "add_as_selected_data_plot" = t."add_as_selected_data_plot",
  "active" = t."active",
  "lab_test_result_fields" = t."lab_test_result_fields",
  "sort_order" = t."sort_order",
  "updated_at" = CURRENT_TIMESTAMP
FROM "lab_test_type_templates" AS t
WHERE u."module_slug" = t."module_slug"
  AND u."option_key" = t."option_key"
  AND t."module_slug" = 'lab-tests';
