-- Seed default lab test type templates for the lab-tests module.
INSERT INTO "lab_test_type_templates" (
  "module_slug",
  "option_key",
  "name",
  "graphic",
  "alias_table",
  "active",
  "lab_test_result_fields",
  "sort_order",
  "created_at",
  "updated_at"
) VALUES
(
  'lab-tests',
  'moisture-content',
  'Moisture Content',
  'graphic_00.png',
  'Moisture Content',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'particle-size-distribution',
  'Particle Size Distribution',
  'graphic_00.png',
  'Particle Size Distribution',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  1,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'atterberg-limits',
  'Atterberg Limits',
  'graphic_00.png',
  'Atterberg Limits',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  2,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'is50',
  'IS50',
  'graphic_00.png',
  'IS50',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  3,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'gs-mechanical-grain-size',
  'GS - Mechanical Grain Size',
  'graphic_00.png',
  'GS - Mechanical Grain Size',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  4,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'w-moisture-content',
  'w - Moisture Content',
  'graphic_00.png',
  'w - Moisture Content',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  5,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'c-consolidation-test',
  'C - Consolidation Test',
  'graphic_00.png',
  'C - Consolidation Test',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  6,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'l-pile',
  'L-Pile',
  'graphic_00.png',
  'L-Pile',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  7,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'hcsi',
  'HCSI',
  'graphic_00.png',
  'HCSI',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  8,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'dr-relative-density',
  'DR - Relative Density',
  'graphic_00.png',
  'DR - Relative Density',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  9,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'k-permeability-coefficient',
  'k - Permeability Coefficient',
  'graphic_00.png',
  'k - Permeability Coefficient',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  10,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'q-triaxial-test',
  'q - Triaxial Test',
  'graphic_00.png',
  'q - Triaxial Test',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  11,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'ucs-unconfined-compressive-strength',
  'UCS - Unconfined Compressive Strength',
  'graphic_00.png',
  'UCS - Unconfined Compressive Strength',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  12,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'sb-shear-box-test',
  'SB - Shear Box Test',
  'graphic_00.png',
  'SB - Shear Box Test',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  13,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'y-unit-weight',
  'Y - Unit Weight',
  'graphic_00.png',
  'Y - Unit Weight',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  14,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'yd-dry-unit-weight',
  'Yd - Dry Unit Weight',
  'graphic_00.png',
  'Yd - Dry Unit Weight',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  15,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'p-density',
  'p - Density',
  'graphic_00.png',
  'p - Density',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  16,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'lab-tests',
  'pd-dry-density',
  'Pd - Dry Density',
  'graphic_00.png',
  'Pd - Dry Density',
  true,
  '[{"id":"result-field-1","name":"","externalAlias":null,"tablogsAlias":null}]'::jsonb,
  17,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("module_slug", "option_key") DO UPDATE SET
  "name" = EXCLUDED."name",
  "graphic" = EXCLUDED."graphic",
  "alias_table" = EXCLUDED."alias_table",
  "active" = EXCLUDED."active",
  "lab_test_result_fields" = EXCLUDED."lab_test_result_fields",
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = CURRENT_TIMESTAMP;
